name: GitHub Actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: "12 4 * * *" # everyday at 4:12 AM UTC

permissions: {}

jobs:
  resetdb-demo:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DEMO_MAIN_DATABASE_URL }}
      SERVER_ENV: "ci-periodic"
      BETTER_AUTH_URL: "http://localhost:3000"
      BETTER_AUTH_SECRET: dummy
      GOOGLE_CLIENT_ID: dummy
      GITHUB_CLIENT_ID: dummy
      GOOGLE_CLIENT_SECRET: dummy
      GITHUB_CLIENT_SECRET: dummy
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3.5.0
        with:
          install: true
          cache: true

      - run: mise install
      - run: mise resetdb-demo
